version: '3.7'
services:
  sm-nginx:
    container_name: sm-nginx
    image: nginx
    restart: always
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/ssl/certificate_crt.pem:/etc/nginx/ssl/certificate.crt
      - ./etc/nginx/ssl/private.key.pem:/etc/nginx/ssl/private.key
      - smsocket:/tmp
    networks:
      - smnet
    depends_on:
      - sm-web
    ports:
      - 443:443

  sm-web:
    container_name: sm-web
    image: sm-web
    build: .
    networks:
      - smnet
    ports:
      - 8080:8080
    depends_on:
      - sm-db
    volumes:
      - ./:/var/www/strawberrymarket
      - smvolume:/var/www/strawberrymarket/app/static
      - smsocket:/tmp
    restart: always
    environment:
      - FLASK_APP=app
      - FLASK_ENV=${FLASK_ENV:-development}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    command: ['sh', './etc/docker-entrypoint.sh']

  sm-db:
    container_name: sm-db
    image: mysql:5.7
    networks:
      - smnet
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: strawberrymarket
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    ports:
      - 3306:3306
    volumes:
      - smvolume:/var/lib/mysql
    restart: always

networks:
  smnet:

volumes:
  smvolume:
  smsocket: